---
- name: Provision VM in AWS with Terraform
  hosts: localhost

  roles:
    - role: terraform-vm-provisioning
      vars:
        infra_state: "{{ infra_state }}"
        force_init: "{{ force_init }}"
        server_count: "{{ server_count }}"
        prefix_instance_name: "{{ instance_name }}"
        instance_env: "{{ instance_env }}"
        project_name: "RHUG_ServiceNow_Ansible_Terraform_Demo"
        git_user: '{{ lookup("env", "git_user") }}'
        git_token: '{{ lookup("env", "git_token") }}'
        git_repo_url: "https://{{ git_user }}:{{ git_token }}@github.com/froberge/ansible_terraform_config.git"
        git_work_dir: "/tmp/terraform/aws"
        pah_pass: '{{ lookup("env", "pah_pass") }}'
        git_name: "AAP service account"
        git_email: "cloudAutomation_aap@company.com"

  tasks:
    - name: Print lb_group_name
      ansible.builtin.debug:
        msg: "{{ instance_env }}_lb"

    - name: Print ws_group_name
      ansible.builtin.debug:
        msg: "{{ instance_env }}_web"


  #   - name: Save the Request_Id for later
  #     ansible.builtin.set_stats:
  #       data:
  #         itsm_request_id: "{{ request_id }}"
