---
- name: Configure JBoss EAP Server
  hosts: all
  gather_facts: false

  # Make sure the system is reachable
  pre_tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts for the first time
      ansible.builtin.setup:

    - name: Print lb_group_name
      ansible.builtin.debug:
        msg: "{{ lb_group_name }}"

    - name: Print ws_group_name
      ansible.builtin.debug:
        msg: "{{ ws_group_name }}_web"


  roles:
    - role: jboss-eap-config
      when: "'{{ ws_group_name }}' in group_names"
