---
- name: Provision VM in Azure with Ansible
  hosts: localhost

  roles:
    - role: azure-vm-provisionning
      vars:
        instance_name_list: "{{ instance_name_list }}"
        project_name: "{{ project_name }}"
        res_group: "{{res_group }}"
        vm_tag_type: "{{vm_tag_type}}"

  tasks:
    block: 
      - name: Ensure firewalld is installed
        yum:
          name: firewalld
          state: present

      - name: Ensure firewalld is running and enabled
        service:
          name: firewalld
          state: started
          enabled: yes

      - name: Allow TCP port 80
        firewalld:
          service: http
          permanent: yes
          state: enabled
          immediate: yes

      - name: Allow TCP port 8080
        firewalld:
          service: http
          permanent: yes
          state: enabled
          immediate: yes

      - name: Allow TCP port 443
        firewalld:
          service: https
          permanent: yes
          state: enabled
          immediate: yes

      - name: Allow TCP port 22
        firewalld:
          port: 22/tcp
          permanent: yes
          state: enabled
          immediate: yes

      - name: Reload firewalld to apply permanent rules
        command: firewall-cmd --reload
    when: "'{{ vm_tag_type }}' in group_names"