---
- name: Provision VM in Azure with Ansible
  hosts: localhost

  roles:
    - role: azure-vm-provisionning
      vars:
        instance_name_list: "{{ instance_name_list }}"
        project_name: "{{ project_name }}"
        res_group: "{{res_group }}"
        instance_env: "{{ instance_env }}"
        vm_type: "{{ vm_type }}"