---
# tasks file for sent_mail
- name: Sending an e-mail using Gmail SMTP servers
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "{{username}}"
    password: "{{password}}"
    to: "{{ recipient }}"
    subject: Ansible Report
    body: System has been successfully provisioned.
