---
# tasks file for haproxy-config
  # epel = Extra Packages for Enterprise Linux
- name: Ensure the epel repo is present
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: install haproxy
  package:
    name: haproxy
    state: present

- name: copy haproxy conf
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc//haproxy/haproxy.cfg
  vars:
    ws_name_tag: {{ ws_name_tag }}

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: true