---
- name: Provision VM in AWS with Terraform
  hosts: localhost

  roles:
    - role: azure-vm-provisionning
      vars:
        instance_name: "webserver"
        project_name: "Ansible_Terraform_Demo"
        res_group: "ansible_demo"
