---
- name: Provision VM in AWS with Terraform
  hosts: localhost

  roles:

    - role: azure-vm-provisionning
      vars:
        instance_name: "lbserver"
        instance_name_list:
          - "lbserver"
        project_name: "{{ project_name }}"
        res_group: "{{res_group }}"
        vm_tag_type: "dev_lb"
      when: create_load_balancer|bool == false

    # - role: azure-vm-provisionning
    #   vars:
    #     instance_name: "{{ instance_name }}"
    #     instance_name_list: "{{ instance_name_list }}"
    #     project_name: "{{ project_name }}"
    #     res_group: "{{res_group }}"
    #     vm_tag_type: "{{vm_tag_type}}"