---
- name: Provision VM in AWS with Terraform
  hosts: localhost

  roles:
    - role: azure-vm-provisionning
      vars:
        instance_name: "{{ instance_name }}"
        project_name: "{{ project_name }}"
        res_group: "{{res_group }}"