---
collections:
  - name: amazon.aws
  - name: azure.azcollection
  - name: ansible.controller
  #- name: cloud.terraform
  - name: google.cloud
  - name: servicenow.itsm
  - name: cloud.terraform
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
